import Head from 'next/head'
import { HiOutlineChevronDoubleUp } from 'react-icons/hi'
import Link from 'next/link'
import { Skills } from '@/components/Skills'
import { Project } from '@/components/Project'
import { About } from '@/components/About'
import { Hero } from '@/components/Hero'
import { Navbar } from '@/components/Navbar'
import { useState, useEffect } from 'react'
import { motion, useScroll } from 'framer-motion'
import { Contact } from '@/components/Contact'

export default function Home() {
  const { scrollYProgress } = useScroll()

  const [darkMode, setDarkMode] = useState(true)

  useEffect(() => {
    if (darkMode) {
      document.body.classList.add('dark-mode')
    } else {
      document.body.classList.remove('dark-mode')
    }
  }, [darkMode])

  const handleDarkModeToggle = () => {
    setDarkMode(!darkMode)
  }

  return (
    <div className={darkMode ? 'dark' : ''} setDarkMode={setDarkMode}>
      <Head>
        <title>Dawit Bezu Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='w-full'>
        <div data-theme='lofi' className='dark:bg-gray-900 p-0 '>
          <div className='md:px-20 lg:px-40 fixed z-30 bg-white w-full dark:bg-black'>
            <Navbar
              darkMode={darkMode}
              handleDarkModeToggle={handleDarkModeToggle}
            />
          </div>

          <Hero />
          <main className='bg-whitesmoke text-gray-700 px-10 md:px-20 lg:px-40 dark:bg-gray-900 p-5'>
            <motion.div
              style={{
                scaleX: scrollYProgress,
                position: 'fixed',
                top: 0,
                left: 0,
                right: 0,
                height: '6px',
                background: 'white',
                transformOrigin: 'left',
              }}
            ></motion.div>{' '}
            <About />
            <Skills />
            <Project />
            <Contact />
          </main>
        </div>
        <div className='flex justify-center py-12'>
          <Link href='/'>
            <div className='rounded-full shadow-md shadow-gray-400 p-4 cursor-pointer hover:scale-110 ease-in duration-300 dark:shadow-cyan-400'>
              <HiOutlineChevronDoubleUp
                className='text-gray-300 dark:text-cyan-300'
                size={30}
              />
            </div>
          </Link>
        </div>
      </div>
    </div>
  )
}
